import * as React from 'react';
import styled from 'styled-components';
import {
  Card,
  initialCard,
  CardCategory,
  CardSubcategory,
  CardCostKind,
} from '../types/cardTypes';
import { TextField } from 'office-ui-fabric-react/lib/TextField';
import { Dropdown, IDropdownOption } from 'office-ui-fabric-react/lib/Dropdown';
import { Slider } from 'office-ui-fabric-react/lib/Slider';
import { Modal } from 'office-ui-fabric-react/lib/Modal';
import { Checkbox } from 'office-ui-fabric-react/lib/Checkbox';
import { initializeIcons } from '@uifabric/icons';
import CardEffectsDetailsList, {
  MoveEffectDirection,
} from '../components/CardEffectsDetailsList';
import CardEffectEditor from './CardEffectEditor';
import { CardEffect } from '../types/cardEffect.types';
import { List } from 'immutable';
import { printCard } from '../utils/cardGenerator';
import { observer } from 'mobx-react';
import {
  CardEditorStore,
  CardEditorStoreModelType,
} from '../models/CardEditorStore';

initializeIcons();

interface State {
  store: CardEditorStoreModelType;
  cardEffectEditor: {
    isOpen: boolean;
    effect: CardEffect | undefined;
    index: number;
  };
}

const StyledCardEditor = styled.div`
  display: grid;
  grid-template-columns: 3fr 2fr;
  grid-gap: 16px;
  padding: 16px;
`;

const CardEditorSection = styled.div`
  display: flex;
  flex-direction: column;
`;

export const Title = styled.div`
  font-family: 'Acme';
  font-size: 24px;
  margin-bottom: 16px;
`;

export const ControlContainer = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
`;

export const Label = styled.label`
  padding: 5px 0;
`;

export const DescriptionContainer = styled.div`
  display: grid;
  grid-template-columns: 200px 1fr;
  grid-gap: 16px;
  margin: 16px 0;
`;

export const CardCostContainer = styled.div`
  display: grid;
  grid-template-columns: 2fr 3fr;
  grid-gap: 16px;
  margin: 16px 0;
`;

const TextFieldContainer = styled.div`
  textarea {
    height: 60vh;
    max-height: 60vh;
  }
`;

@observer
class CardEditor extends React.Component<object, State> {
  componentWillMount() {
    this.setState({
      store: CardEditorStore.create({
        currentCard: printCard(initialCard),
        autoGenerateDescription: true,
      }),
      cardEffectEditor: {
        isOpen: false,
        effect: undefined,
        index: -1,
      },
    });
    this.openAddCardEffectEditor = this.openAddCardEffectEditor.bind(this);
    this.openUpdateCardEffectEditor = this.openUpdateCardEffectEditor.bind(
      this
    );
    this.closeCardEffectEditor = this.closeCardEffectEditor.bind(this);
    this.changeCardEffectOrder = this.changeCardEffectOrder.bind(this);

    this.addCardEffect = this.addCardEffect.bind(this);
    this.updateCardEffect = this.updateCardEffect.bind(this);
    this.removeCardEffect = this.removeCardEffect.bind(this);
  }

  updateCurrentCard(card: Partial<Card>) {
    this.state.store.updateCurrentCard(card);
  }

  openAddCardEffectEditor() {
    this.setState({
      cardEffectEditor: {
        isOpen: true,
        effect: undefined,
        index: -1,
      },
    });
  }

  openUpdateCardEffectEditor(index: number) {
    this.setState({
      cardEffectEditor: {
        isOpen: true,
        effect: this.state.store.currentCard.effectsList.find(
          (_, i) => i === index
        ),
        index,
      },
    });
  }

  closeCardEffectEditor() {
    this.setState({
      cardEffectEditor: {
        isOpen: false,
        effect: undefined,
        index: -1,
      },
    });
  }

  addCardEffect(effect: CardEffect) {
    this.updateCurrentCard({
      effects: this.state.store.currentCard.effectsList.push(effect),
    });
    this.closeCardEffectEditor();
  }

  updateCardEffect(effect: CardEffect, index: number) {
    this.updateCurrentCard({
      effects: List<CardEffect>(
        this.state.store.currentCard.effectsList.splice(index, 1, effect)
      ),
    });
    this.closeCardEffectEditor();
  }

  removeCardEffect(index: number) {
    this.updateCurrentCard({
      effects: this.state.store.currentCard.effectsList.remove(index),
    });
  }

  /** Remove the effect at index i from the list, then re-insert it at a new index position. */
  changeCardEffectOrder(index: number, direction: MoveEffectDirection) {
    const movedEffect = this.state.store.currentCard.effectsList.find(
      (_, i) => i === index
    );
    const newIndex = index + (direction === 'Up' ? -1 : 1);
    this.updateCurrentCard({
      effects: this.state.store.currentCard.effectsList
        .remove(index)
        .insert(newIndex, movedEffect),
    });
  }

  render() {
    return (
      <StyledCardEditor>
        <CardEditorSection>
          <Title>Card Editor</Title>
          <TextField
            label="Name"
            onChanged={(value: string) => {
              this.updateCurrentCard({ name: value });
            }}
          />

          <Dropdown
            label="Category"
            selectedKey={this.state.store.currentCard.category}
            options={Object.keys(CardCategory).map(key => {
              return { key, text: CardCategory[key] };
            })}
            onChanged={({ key }: IDropdownOption) => {
              this.updateCurrentCard({ category: CardCategory[key] });
            }}
          />

          <Dropdown
            label="Subcategories"
            multiSelect
            options={Object.keys(CardSubcategory)
              .map(key => {
                return {
                  key,
                  text: CardSubcategory[key],
                };
              })
              .sort()}
            onChanged={({ key, selected }: IDropdownOption) => {
              if (selected) {
                this.updateCurrentCard({
                  subcategories: [
                    ...this.state.store.currentCard.subcategories,
                    CardSubcategory[key],
                  ].sort(),
                });
              } else {
                this.updateCurrentCard({
                  /* tslint:disable no-any */
                  subcategories: this.state.store.currentCard.subcategories
                    .filter(_ => _ !== CardSubcategory[key])
                    .sort() as any,
                });
              }
            }}
            onRenderTitle={(options: IDropdownOption[]) => {
              return (
                <>
                  {options
                    .map(_ => _.text)
                    .sort()
                    .join(', ')}
                </>
              );
            }}
          />

          <Label>Description</Label>
          <DescriptionContainer>
            <Checkbox
              label="Auto generate description"
              checked={this.state.store.autoGenerateDescription}
              onChange={() => {
                this.state.store.toggleAutoGenerateDescription();
              }}
            />
            <TextField
              disabled={this.state.store.autoGenerateDescription}
              value={this.state.store.currentCard.description}
              onChanged={(value: string) => {
                this.updateCurrentCard({ description: value });
              }}
            />
          </DescriptionContainer>

          <CardCostContainer>
            <Dropdown
              label="Card Cost Kind"
              selectedKey={this.state.store.currentCard.cost.kind}
              options={Object.keys(CardCostKind).map(key => {
                return { key, text: CardCostKind[key] };
              })}
              onChanged={({ key }: IDropdownOption) => {
                this.updateCurrentCard({
                  cost: {
                    /* tslint:disable no-any */
                    ...(this.state.store.currentCard.cost as any),
                    kind: CardCostKind[key],
                  },
                });
              }}
            />
            <ControlContainer>
              <Label>Card Cost Value</Label>
              <Slider
                value={this.state.store.currentCard.cost.value}
                min={0}
                max={10}
                step={1}
                onChange={value => {
                  this.updateCurrentCard({
                    cost: {
                      /* tslint:disable no-any */
                      ...(this.state.store.currentCard.cost as any),
                      value,
                    },
                  });
                }}
              />
            </ControlContainer>
          </CardCostContainer>

          <ControlContainer>
            <Label>Card Effects</Label>
            <CardEffectsDetailsList
              items={this.state.store.currentCard.effectsList.toArray()}
              onAdd={this.openAddCardEffectEditor}
              onUpdate={this.openUpdateCardEffectEditor}
              onRemove={this.removeCardEffect}
              onMove={this.changeCardEffectOrder}
            />
          </ControlContainer>
        </CardEditorSection>

        <CardEditorSection>
          <Title>Card JSON</Title>
          <TextFieldContainer>
            <TextField
              multiline
              autoAdjustHeight
              readOnly
              value={JSON.stringify(this.state.store.currentCard, undefined, 2)}
            />
          </TextFieldContainer>
        </CardEditorSection>

        <Modal
          isOpen={this.state.cardEffectEditor.isOpen}
          onDismiss={() =>
            this.setState({
              cardEffectEditor: { isOpen: false, effect: undefined, index: -1 },
            })
          }
        >
          {this.state.cardEffectEditor.isOpen && (
            <CardEffectEditor
              cardEffect={this.state.cardEffectEditor.effect}
              cardEffectIndex={this.state.cardEffectEditor.index}
              onCancel={this.closeCardEffectEditor}
              onAdd={this.addCardEffect}
              onUpdate={this.updateCardEffect}
            />
          )}
        </Modal>
      </StyledCardEditor>
    );
  }
}

export default CardEditor;
