import { types } from 'mobx-state-tree';
import { Card } from './Card';
import { Card as CardType } from '../types/cardTypes';

export const CardEditorStore = types
  .model('CardEditor', {
    currentCard: Card,
    autoGenerateDescription: types.boolean,
  })
  .actions(self => ({
    updateCurrentCard(card: Partial<CardType>) {
      self.currentCard = {
        ...self.currentCard,
        /* tslint:disable no-any unfortunately because MobX State Tree types are bad... */
        ...(card as any),
        effects: card.effects ? card.effects : self.currentCard.effects,
      };
    },
    toggleAutoGenerateDescription() {
      self.autoGenerateDescription = !self.autoGenerateDescription;
    },
  }));

export type CardEditorStoreModelType = typeof CardEditorStore.Type;
